/**
 * ⛔ THE AGENT TREE, RENDERED FROM THE REGISTRY — because a document nobody generates is a document
 * that disagrees with the code within a week.
 *
 * Peter: "draw out our agent tree? let's keep a dedicated doc showing what agents we have."
 *
 * A dedicated doc is the right thing to want and the wrong thing to type. Everything in it already
 * exists as data in `core/jobs.ts`: what each agent asks, why it exists, what it reads, what counts
 * as a finding, what it may never do. Typing a second copy makes two records of one fact, and the
 * typed one wins because it is the one people read — until it is wrong, which nothing detects.
 *
 * So this renders it, a test asserts the committed file still matches, and changing an agent
 * changes the doc or fails the build.
 */
import { AGENTS, AREAS, CASCADE, KINDS, LAYERS, type Agent } from "./jobs.js";

const bullet = (xs: string[]): string => xs.map((x) => `- ${x}`).join("\n");

/**
 * ⛔ THE TREE AS A DIAGRAM, because "tree" was the word and a list is not one. What it shows is the
 * only structure here that matters: every agent answers a question about the WHOLE map, which is
 * why none of them is scoped to a file and why a consistency question is answerable at all.
 */
function diagram(): string {
  const node = (a: Agent) => `  ${a.name.replace(/-/g, "_")}["${a.name}<br/><i>${a.asks.replace(/"/g, "'")}</i>"]`;
  return [
    "```mermaid",
    "flowchart LR",
    "  subgraph REVIEWERS[\"reviewers — each asks one question about the whole\"]",
    "    direction TB",
    ...AGENTS.map(node),
    "  end",
    "  subgraph MAP[\"the map — territory every reviewer reads\"]",
    "    direction TB",
    ...AREAS.map((a) => `    ${a.name}["${a.name}<br/><i>${a.owns.join(", ")}</i>"]`),
    "  end",
    "  REVIEWERS --> MAP",
    "```",
  ].join("\n");
}

export function agentsDoc(): string {
  const out: string[] = [];
  out.push("# The reviewers");
  out.push("");
  out.push("> ⛔ **Generated from `src/core/jobs.ts`. Do not edit this file.**");
  out.push("> `productos v2 agents --out AGENTS.md` rewrites it, and a test fails if it drifts.");
  out.push("");
  out.push(
    "Every one of these answers **one question about the whole system**. None is scoped to a file, " +
      "and that is deliberate: the failure they exist to catch is nobody owning *is this concept " +
      "present everywhere it needs to be*, which is a property of the whole and invisible from " +
      "inside any one layer."
  );
  out.push("");
  out.push(
    "⛔ **Every one judges. None may write.** Enforced at install, not hoped: an agent's tool list " +
      "is derived from the capabilities it declares, and no capability a judge can declare maps to " +
      "a writing tool. A reviewer that repairs what it finds hides how often it fires, and how " +
      "often it fires is the only measure of whether the model is holding."
  );
  out.push("");
  out.push(diagram());
  out.push("");

  out.push("## What each one is for");
  for (const a of AGENTS) {
    out.push("");
    out.push(`### \`${a.name}\`${a.prompt ? "" : "  — ⛔ no prompt written yet"}`);
    out.push("");
    out.push(`**Asks:** ${a.asks}`);
    out.push("");
    out.push(`**Exists because:** ${a.because}`);
    out.push("");
    out.push("**Reads, in this order:**");
    out.push(bullet(a.reads));
    out.push("");
    out.push("**A finding is:**");
    out.push(bullet(a.finds));
    out.push("");
    out.push("**⛔ Never:**");
    out.push(bullet(a.never));
    out.push("");
    out.push(`**Needs:** ${a.needs.join(" · ")}${a.prompt ? `  ·  **Prompt:** \`${a.prompt}\`` : ""}`);
  }

  out.push("");
  out.push("## The map they read");
  out.push("");
  out.push(
    "Territory, not ownership. Nobody is assigned an area — an agent reads this to know what " +
      "*everywhere* means, and a test asserts every layer is held exactly once and every file in the " +
      "track is on it. A file missing from the map is a place no agent will look."
  );
  out.push("");
  out.push("| area | layers | files |");
  out.push("|---|---|---|");
  for (const a of AREAS) out.push(`| **${a.name}** | ${a.owns.join(", ")} | ${a.files.map((f) => `\`${f}\``).join(" ")} |`);

  out.push("");
  out.push("## Where a change has to reach");
  out.push("");
  out.push(
    "`productos v2 change` routes a piece of feedback by its kind, and refuses to close while a " +
      "layer it must reach is unverified. The routing is a table rather than a judgement because the " +
      "layer skipped from memory is always the same one — `instruct`, the authoring instructions, " +
      "which is how a concept can be perfect in the schema and written by nobody."
  );
  out.push("");
  out.push("| kind of change | must reach |");
  out.push("|---|---|");
  for (const k of KINDS) out.push(`| **${k}** | ${CASCADE[k]!.join(" · ")} |`);
  out.push("");
  out.push(`All layers: ${LAYERS.map((l) => `\`${l}\``).join(" · ")}`);

  out.push("");
  out.push("## Which model runs each");
  out.push("");
  out.push(
    "⛔ **No agent names a model.** The spec says what an agent is for, what it must never do, and " +
      "which capabilities it needs; the project says who runs it. An adapter reads both at install " +
      "time and writes whatever the host wants — so the same reviewer runs under a different model " +
      "in a different repo, and a test fails if a model name ever appears in a definition."
  );
  out.push("");
  out.push("```yaml");
  out.push("# productos/config.yaml");
  out.push("agents:");
  out.push("  default_model: sonnet");
  out.push("  model:");
  out.push("    truthfulness: opus        # this one reads the code as well as the corpus");
  out.push("    consistency: opus");
  out.push("  effort:");
  out.push("    truthfulness: high");
  out.push("  off:");
  out.push("    architecture: reviewed by hand here — one promise per subsystem already");
  out.push("```");
  out.push("");
  out.push(
    "⛔ `off` **removes** the agent rather than skipping it. One left on disk from a previous " +
      "install is one the host can still run while the config says otherwise."
  );
  out.push("");
  const missing = AGENTS.filter((a) => !a.prompt);
  if (missing.length) {
    out.push(`## ⛔ ${missing.length} named here with no prompt written`);
    out.push("");
    out.push(bullet(missing.map((m) => `\`${m.name}\` — ${m.asks}`)));
    out.push("");
    out.push("Named so the absence is visible rather than implied.");
  }
  out.push("");
  return out.join("\n");
}
